# Modeling
### Author: Ehsan Gharib-Nezhad


In [40]:
# Load Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from nltk.probability import FreqDist
import re
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import  LabelEncoder, OneHotEncoder
import random

# |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
# Dataset 1: Human dataset
# |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||

In [23]:
# Load datasets
human = pd.read_table('../datasets/human.txt')

In [24]:
human.head()

sequence  class
0  ATGCCCCAACTAAATACTACCGTATGGCCCACCATAATTACCCCCA...      4
1  ATGAACGAAAATCTGTTCGCTTCATTCATTGCCCCCACAATCCTAG...      4
2  ATGTGTGGCATTTGGGCGCTGTTTGGCAGTGATGATTGCCTTTCTG...      3
3  ATGTGTGGCATTTGGGCGCTGTTTGGCAGTGATGATTGCCTTTCTG...      3
4  ATGCAACAGCATTTTGAATTTGAATACCAGACCAAAGTGGATGGTG...      3

In [25]:
human.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4380 entries, 0 to 4379
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sequence  4380 non-null   object
 1   class     4380 non-null   int64 
dtypes: int64(1), object(1)
memory usage: 68.6+ KB


## One-hot encoding DNA Sequence

In [37]:
def string_to_array(seq_string):
    seq_string = seq_string.lower()
    seq_string = re.sub('[^acgt]', 'z', seq_string)
    seq_string = np.array(list(seq_string))
    return seq_string


In [41]:
def one_hot_encoder(seq_string):
    label_encoder = LabelEncoder()
    label_encoder.fit(np.array(['a','c','g','t','z']))
    int_encoded = label_encoder.transform(seq_string)
    onehot_encoder = OneHotEncoder(sparse=False, dtype=int)
    int_encoded = int_encoded.reshape(len(int_encoded), 1)
    onehot_encoded = onehot_encoder.fit_transform(int_encoded)
    return onehot_encoded


In [42]:
one_hot_encoder(string_to_array(human['sequence'][0]))

array([[1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0,

In [45]:
X =  map(one_hot_encoder, human['sequence']) 

In [52]:
human['hotCode'] = [ one_hot_encoder(string_to_array(x)) for x in human['sequence'] ]

In [53]:
human

sequence  class  \
0     ATGCCCCAACTAAATACTACCGTATGGCCCACCATAATTACCCCCA...      4   
1     ATGAACGAAAATCTGTTCGCTTCATTCATTGCCCCCACAATCCTAG...      4   
2     ATGTGTGGCATTTGGGCGCTGTTTGGCAGTGATGATTGCCTTTCTG...      3   
3     ATGTGTGGCATTTGGGCGCTGTTTGGCAGTGATGATTGCCTTTCTG...      3   
4     ATGCAACAGCATTTTGAATTTGAATACCAGACCAAAGTGGATGGTG...      3   
...                                                 ...    ...   
4375  ATGGAAGATTTGGAGGAAACATTATTTGAAGAATTTGAAAACTATT...      0   
4376  ATGCAGTCCTTTCGGGAGCAAAGCAGTTACCACGGAAACCAGCAAA...      6   
4377  ATGCAGTCCTTTCGGGAGCAAAGCAGTTACCACGGAAACCAGCAAA...      6   
4378  ATGGGGCACCTGGTTTGCTGTCTGTGTGGCAAGTGGGCCAGTTACC...      6   
4379  ATGCAGTCCTTTCGGGAGCAAAGCAGTTACCACGGAAACCAGCAAA...      6   

                                                hotCode  
0     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
1     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [1,...  
2     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
3     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
4     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
...                                                 ...  
4375  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
4376  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
4377  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
4378  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  
4379  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...  

[4380 rows x 3 columns]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(human['hotCode'], 
                                                    human['class'], 
                                                    test_size = 0.20, 
                                                    random_state=42)

In [57]:
X_train, X_test, y_train, y_test

(2519    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 1767    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [1,...
 1056    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [1,...
 2860    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 3303    [[0, 0, 0, 1], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
                               ...                        
 3444    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 466     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 3092    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 3772    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 860     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [1,...
 Name: hotCode, Length: 3504, dtype: object,
 175     [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 3660    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 3331    [[0, 0, 0, 0, 1], [0, 0, 1, 0, 0], [0, 0, 0, 1...
 2702    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
 3085    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 0, 1, 0], [0,...
           

In [56]:
#The fit method of KNN class is called to train the algorithm on the training data, 
#which is passed as a parameter to the fit method
from sklearn.neighbors import KNeighborsClassifier
KNNclassifier = KNeighborsClassifier(n_neighbors=5)
KNNclassifier.fit(X_train, y_train)

ValueError: setting an array element with a sequence.

# Modeling

---

We may want to test lots of different values of hyperparameters in our CountVectorizer.

In [6]:
# Select a percentage of the whole data randomly ___________________________________________
total_kmer_numbers = len(human['kmers'])
random_numbers = random.sample(range(total_kmer_numbers), int(total_kmer_numbers*.01) )
# image_path_list_1D_randomized = image_path_list_1D[[random_numbers[:]]]
# target_from_image_path_list_1D_randomized = [path_image.split(os.sep)[-2] 
#                                              for path_image in image_path_list_1D_randomized ]

In [7]:
X = human['kmers'].iloc[random_numbers]
y = human['class'].iloc[random_numbers]

In [8]:
# Split the data into the training and testing sets.
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size=0.33,
                                                    stratify=y,
                                                    random_state=42)

## Baseline accuracy

We need to calculate baseline accuracy in order to tell if our model is better than null model.

In [9]:
pd.DataFrame(y_train).value_counts(normalize=True), pd.DataFrame(y_test).value_counts(normalize=True)

(class
 6        0.274687
 0        0.149346
 1        0.141271
 3        0.123141
 2        0.114664
 4        0.112570
 5        0.084321
 dtype: float64,
 class
 6        0.274684
 0        0.149348
 1        0.141277
 3        0.123138
 2        0.114662
 4        0.112567
 5        0.084324
 dtype: float64)

In [10]:
cv = CountVectorizer()
Xcv_train = cv.fit_transform(X_train)

In [11]:
print(Xcv_train)

  (0, 62596)	1
  (1, 59488)	1
  (2, 50196)	1
  (3, 66867)	1
  (4, 58197)	1
  (5, 48394)	1
  (6, 66897)	1
  (7, 46583)	1
  (8, 37063)	1
  (9, 28663)	1
  (10, 37807)	1
  (11, 62896)	1
  (12, 27722)	1
  (13, 47443)	1
  (14, 38551)	1
  (15, 39829)	1
  (16, 6206)	1
  (17, 56932)	1
  (18, 38726)	1
  (19, 56612)	1
  (20, 67713)	1
  (21, 1640)	1
  (22, 27721)	1
  (23, 56529)	1
  (24, 29395)	1
  :	:
  (295570, 24181)	1
  (295571, 12939)	1
  (295572, 20258)	1
  (295573, 59306)	1
  (295574, 36609)	1
  (295575, 11774)	1
  (295576, 15149)	1
  (295577, 61847)	1
  (295578, 69104)	1
  (295579, 32357)	1
  (295580, 24915)	1
  (295581, 19615)	1
  (295582, 46865)	1
  (295583, 70909)	1
  (295584, 25960)	1
  (295585, 24182)	1
  (295586, 28399)	1
  (295587, 28687)	1
  (295588, 37825)	1
  (295589, 48446)	1
  (295590, 49902)	1
  (295591, 10789)	1
  (295592, 45384)	1
  (295593, 26263)	1
  (295594, 63209)	1


In [12]:
# to convert sparse matrix to dense matrix
Xcv_train_df = pd.DataFrame(Xcv_train.todense(),
                           columns = cv.get_feature_names() )
Xcv_train_df.head()

aa  aaa  aaaa  aaaaa  aaaaaa  aaaaaaa  aaaaaaaa  aaaaaaaag  aaaaaaac  \
0   0    0     0      0       0        0         0          0         0   
1   0    0     0      0       0        0         0          0         0   
2   0    0     0      0       0        0         0          0         0   
3   0    0     0      0       0        0         0          0         0   
4   0    0     0      0       0        0         0          0         0   

   aaaaaaag  ...  ttttttcc  ttttttcct  ttttttcg  ttttttctc  ttttttctt  \
0         0  ...         0          0         0          0          0   
1         0  ...         0          0         0          0          0   
2         0  ...         0          0         0          0          0   
3         0  ...         0          0         0          0          0   
4         0  ...         0          0         0          0          0   

   ttttttg  ttttttgc  ttttttgct  ttttttt  tttttttg  
0        0         0          0        0         0  
1        0         0          0        0         0  
2        0         0          0        0         0  
3        0         0          0        0         0  
4        0         0          0        0         0  

[5 rows x 73084 columns]

In [13]:
Xcv_train_df.shape

(295595, 73084)

In [14]:
# Transform the test corpus.
Xcv_test = cv.transform(X_test)

In [15]:
# to convert sparse matrix to dense matrix
Xcv_test_df = pd.DataFrame(Xcv_test.todense(),
                           columns = cv.get_feature_names() )
Xcv_test_df.head()

aa  aaa  aaaa  aaaaa  aaaaaa  aaaaaaa  aaaaaaaa  aaaaaaaag  aaaaaaac  \
0   0    0     0      0       0        0         0          0         0   
1   0    0     0      0       0        0         0          0         0   
2   0    0     0      0       0        0         0          0         0   
3   0    0     0      0       0        0         0          0         0   
4   0    0     0      0       0        0         0          0         0   

   aaaaaaag  ...  ttttttcc  ttttttcct  ttttttcg  ttttttctc  ttttttctt  \
0         0  ...         0          0         0          0          0   
1         0  ...         0          0         0          0          0   
2         0  ...         0          0         0          0          0   
3         0  ...         0          0         0          0          0   
4         0  ...         0          0         0          0          0   

   ttttttg  ttttttgc  ttttttgct  ttttttt  tttttttg  
0        0         0          0        0         0  
1        0         0          0        0         0  
2        0         0          0        0         0  
3        0         0          0        0         0  
4        0         0          0        0         0  

[5 rows x 73084 columns]

In [16]:
Xcv_test_df.shape

(145593, 73084)

In [ ]:
#The fit method of SVC class is called to train the algorithm on the training data, 
#which is passed as a parameter to the fit method
from sklearn.svm import SVC
svclassifier = SVC(kernel='linear')
svclassifier.fit(Xcv_train, y_train)

In [ ]:
svclassifier.score(Xcv_train, y_train) , svclassifier.score(Xcv_test, y_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svclassifier.predict(Xcv_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

In [17]:
#The fit method of KNN class is called to train the algorithm on the training data, 
#which is passed as a parameter to the fit method
from sklearn.neighbors import KNeighborsClassifier
KNNclassifier = KNeighborsClassifier()
KNNclassifier.fit(Xcv_train, y_train)

KNeighborsClassifier()

In [18]:
KNNclassifier.score(Xcv_train, y_train) , KNNclassifier.score(Xcv_test, y_test)

(0.2762259172178149, 0.17767337715412143)

In [20]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = KNNclassifier.predict(Xcv_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[ 3796  2588  1517  6378  1278   626  5561]
 [ 3422  2952  1437  5739  1320   512  5187]
 [ 2775  1957  1286  4898   990   457  4331]
 [ 2965  2227  1325  5528  1065   477  4341]
 [ 2693  1975  1146  4899  1106   426  4144]
 [ 1997  1437   877  3654   785   358  3169]
 [ 6582  4691  2899 11555  2421  1002 10842]]
              precision    recall  f1-score   support

           0       0.16      0.17      0.17     21744
           1       0.17      0.14      0.15     20569
           2       0.12      0.08      0.09     16694
           3       0.13      0.31      0.18     17928
           4       0.12      0.07      0.09     16389
           5       0.09      0.03      0.04     12277
           6       0.29      0.27      0.28     39992

    accuracy                           0.18    145593
   macro avg       0.15      0.15      0.14    145593
weighted avg       0.18      0.18      0.17    145593



In [ ]:
#The fit method of KNN class is called to train the algorithm on the training data, 
#which is passed as a parameter to the fit method
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier()
RFC.fit(Xcv_train, y_train)

In [ ]:
y_pred = RFC.predict(Xcv_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))